### ISSUE TITLE
Feature Request - Trading Tax Cap

### ISSUE THREAD

**Issue by Dirty-git** [Kenya-DK/quantframe-react#20]
Similarly to the "Average Price Cap" setting, I would like to request a setting for "Trading Tax Cap".

Use case: When low on credits, I would like to flip items with a small trading tax.
Reasoning: Posting orders that you cannot fulfil breaks Warframe Market ToS.
Function: The new setting would introduce an additional filter when looking at suitable items to resell and filter out those items that have a Trading Tax over the set cap.

**Comment by Kenya-DK** [comment]
I can add that

**Comment by Kenya-DK** [comment]
Is add in the new release
