### ISSUE TITLE
Price Scraper hanging at 0% (HTTPS Cert issue with relics.run)

### ISSUE THREAD

**Issue by ArchOwlen** [Kenya-DK/quantframe-react#22]
This is more likely a temporary issue, but I'm going ahead and creating this issue in hopes it can be visualized to the user in case it happens to them, so they know how to fix it

Logs say the relics.run certificate is invalid, and is returning code 500

So I'm guessing
1. Their certificate ran out
2. My system clock needs adjusting (I'm going to reboot after posting this to double check)

I got the same invalid certificate error when visiting the site directly, which is unrelated to Quantframe, but still worth noting to the user what the issue was imo

Side note, restarting Quantframe to try re-starting the scraper also deleted all my data somehow, although I'm not sure how to check how this happened (so I am unable to supply enough info to properly report the issue)

**Comment by ArchOwlen** [comment]
Can confirm that is is an issue with relics.run, not my PC's time

**Comment by ArchOwlen** [comment]
Issue has been fixed on relics.run 's side, but may still be worth putting in a visual error for the user

**Comment by Kenya-DK** [comment]
No need for it is on the server side.
