### ISSUE TITLE
first thing it did ..

### ISSUE THREAD

**Issue by LiamC-AI** [Kenya-DK/quantframe-react#26]
When i did hit the "start live trading" (just wanted to test drive the app, while i disabled auto trading in settings as i thought maybe i would eventually see a simulation / market infos/analysis about action the app ought to operate) => the app deleted all my active sell orders in WFM (...), that's not super beginner friendly for a start, didn't even saw any warning for this could happen.

**Comment by LiamC-AI** [comment]
1.0.4
Steps i made :
- i logged the app with wfm. got into settings and unchecked auto-trade & report to WFM.
- in Live trading tab, executed price scrapper, then started live trading, its when it proceeded to wipe my existing orders.

was just a quick test to see what happens / if any info would be displayed about the underlying analysis & method. i thought unchecking the aformentionned in the general seetings would avoid the app messing with existing entries in my WFM account.

**Comment by Kenya-DK** [comment]
![Quantframe_UzkZFC4U4Q](https://github.com/user-attachments/assets/771f2ba6-c735-400e-bdda-eff293c1e6cd)
I add a pop up

**Comment by LiamC-AI** [comment]
There we go, thanks.

![image](https://github.com/user-attachments/assets/6ad79c81-8e80-427a-86ef-561416346d16)

for some reason github displays this so i thought it was the last version didn't looked further, clicked on it, downlaoded and installed, looks like there was no warning back then.

**Comment by Kenya-DK** [comment]
1.0.4 is a stable version and 1.2.X is Pre-release
