### ISSUE TITLE
error

### ISSUE THREAD

**Issue by letroflom** [Kenya-DK/quantframe-react#32]
←[36m[←[0m2024-10-15 07:16:32←[36m]←[0m ←[36m[←[0m←[1;34mDEBUG←[0m←[36m]←[0m ←[36m[←[0m←[1;35mWarframeMarket:Order:GetOrdersByItem←[0m←[36m]←[0m ←[37mOrders for cinta_upper_limb_blueprint were fetched. found: 276←[0m
←[36m[←[0m2024-10-15 07:16:33←[36m]←[0m ←[36m[←[0m←[1;34mDEBUG←[0m←[36m]←[0m ←[36m[←[0m←[1;35mWarframeMarket:Item:GetItem←[0m←[36m]←[0m ←[37mGettting item: cinta_upper_limb_blueprint←[0m
←[36m[←[0m2024-10-15 07:16:35←[36m]←[0m ←[36m[←[0m←[1;31mERROR←[0m←[36m]←[0m ←[36m[←[0m←[1;35mWarframeMarket:Order:Create←[0m←[36m]←[0m ←[37msrc\wfm_client\modules\order.rs:114:21, There was an error creating order The request failed with status code 400 to the url: https://api.warframe.market/v1/profile/orders with the following message: subtype: app.form.field_required, {"ApiError":{"body":{"item":"645104637ec190030e510936","order_type":"sell","platinum":10,"quantity":1,"visible":true},"error":"ApiError","messages":["subtype: app.form.field_required"],"method":"POST","raw_response":"{\"error\": {\"subtype\": [\"app.form.field_required\"]}}","statusCode":400,"url":"https://api.warframe.market/v1/profile/orders"}}←[0m
←[36m[←[0m2024-10-15 07:16:36←[36m]←[0m ←[36m[←[0m←[1;32mINFO←[0m←[36m]←[0m ←[36m[←[0m←[1;35mLiveScraper←[0m←[36m]←[0m ←[37mLoop live scraper is stopped←[0m

**Comment by Kenya-DK** [comment]
Delete the item it is trydin to sell.

**Comment by letroflom** [comment]
ye,ive deleted, but you might wanna fix it or something, im not really sure how it works from code part, so just decided to tell you about that

**Comment by Kenya-DK** [comment]
> ye,ive deleted, but you might wanna fix it or something, im not really sure how it works from code part, so just decided to tell you about that

It is fix in the pre-relese



> bugged as well @Kenya-DK
> 
> There was an error sending the request: error sending request for url (https://api.warframe.market/v1/items/cascadia_flare/orders): error trying to connect: Удаленный хост принудительно разорвал существующее подключение. (os error 10054) The request failed with status code 500 to the url: https://api.warframe.market/v1/items/cascadia_flare/orders with the following message: error sending request for url (https://api.warframe.market/v1/items/cascadia_flare/orders): error trying to connect: Удаленный хост принудительно разорвал существующее подключение. (os error 10054), {"ApiError":{"body":{},"error":"UnknownError","messages":["error sending request for url (https://api.warframe.market/v1/items/cascadia_flare/orders): error trying to connect: Удаленный хост принудительно разорвал существующее подключение. (os error 10054)"],"method":"GET","statusCode":500,"url":"[https://api.warframe.market/v1/items/cascadia_flare/orders"}}←[0m](https://api.warframe.market/v1/items/cascadia_flare/orders%22%7D%7D%E2%86%90%5B0m) ←[36m[←[0m2024-10-15 07:46:06←[36m]←[0m ←[36m[←[0m←[1;32mINFO←[0m←[36m]←[0m ←[36m[←[0m←[1;35mLiveScraper←[0m←[36m]←[0m ←[37mLoop live scraper is stopped←[0m

Looks like a wfm error

**Comment by letroflom** [comment]
okay
