### ISSUE TITLE
wtb enhancer 

### ISSUE THREAD

**Issue by letroflom** [Kenya-DK/quantframe-react#33]
so we do have autobuy order mode, that creates WTB on it own, but
i guess it would be good as well, if we could add WTB orders on our own

for example: im building nataruk atm, so i need several mods for him like galvanizes and etc
so we do add them as WTB order, and quantframe makes its "cheaper" as much as it can, so till someone sells it to us

i can add WTB orders on my own through WFM, but after quantframe trading restart he also deletes orders made from the other place(basically just deletes every order, which is not really a problem tbh, but sometimes triggers)

sorry for my bad english, i guess you understood my suggest

**Comment by Kenya-DK** [comment]
It it in the works.

Will be add in the next version
