### ISSUE TITLE
Tax Cap Doesn't Work Properly

### ISSUE THREAD

**Issue by N-Gine111** [Kenya-DK/quantframe-react#35]
Buy order just ignores tax cap if I have high credit item for sell like prime mods. It excludes every other items that's above 12,000 credits, but not these 5 specifically, since I have a sell order for them.
![Quantframe_241026-191730](https://github.com/user-attachments/assets/8e285d43-4fea-4d79-91ad-435c834bfca5)

**Comment by Kenya-DK** [comment]
What is your settings and what ver are y using.

Det y save and restated the livetrader??

**Comment by Kenya-DK** [comment]
Try to delete all ordres

**Comment by Kenya-DK** [comment]
I wil see if i can recreate it when i get home form work later.

**Comment by Kenya-DK** [comment]
I just tryde it and it works fine here
