### ISSUE TITLE
Laptop touchpad scrolling moves the whole UI

### ISSUE THREAD

**Issue by Skynetexe** [Kenya-DK/quantframe-react#5]
Hello,

Loving the current version, but it has a common problem where scrolling with my laptops built-in touchpad moves the whole UI up or down past what is allowed on a regular mouse's scroll wheel. Same happens for every page.

![image](https://github.com/Kenya-DK/quantframe-react/assets/117482613/bbcd7b65-845e-47c7-980f-ed265d8f0a6b)
![image](https://github.com/Kenya-DK/quantframe-react/assets/117482613/69e11b7c-f1bb-48ea-9c70-a30c187e75ac)
![image](https://github.com/Kenya-DK/quantframe-react/assets/117482613/ffc72f6c-360b-431b-bf82-a6ab1954b10e)

Extremely minor and inconsequential I'm aware
Keep the amazing work up!

**Comment by Kenya-DK** [comment]
Can you try to mack a vidio to show it.
Dont have a touchpad so cant test it

**Comment by Skynetexe** [comment]
of course, let me get some recording software up and running,

**Comment by Skynetexe** [comment]
Here's the quick video:

https://github.com/Kenya-DK/quantframe-react/assets/117482613/0dec3b1a-8644-4080-9eb6-84587762f167

Hope it helps

**Comment by Skynetexe** [comment]
I just found that it also does the thing for left and right schooling.

https://github.com/Kenya-DK/quantframe-react/assets/117482613/314eb05d-9902-4258-a0e2-d6b212ec1bd2

The behavior is seems like its that of a regular website

**Comment by Kenya-DK** [comment]
Wel it is a website embede in a app
