### ISSUE TITLE
Let you choose mod rank when selling?

### ISSUE THREAD

**Issue by BernardoKaluza** [Kenya-DK/quantframe-react#6]
Is there an option, or easy way to implement it so there can be an option to set the rank of the mod you are selling?

For example, I have some shell shock mods that currently sell for 60p unranked, and as the program always deletes your open orders, I thought about adding them to the live trading tab, however for some reason people are selling it maxed for 80p, and the program when it creates the listing assumes they are maxed and creates a listing for 80p even though it only costs 200 endo so no one will buy it maxed.

I know it's quite the edge case but it would be a nice QOL feature.

**Comment by Kenya-DK** [comment]
As of now the app can only do max rank.
and this will not cheance as it require a lot of time

**Comment by Kenya-DK** [comment]
As of now the app can only do max rank.
and this will not cheance as it require a lot of time
