### ISSUE TITLE
Could not parse error during live trading (1.02)

### ISSUE THREAD

**Issue by mmaalex22112** [Kenya-DK/quantframe-react#9]
During live trading, this issue will occur. 

`[2024-04-04 00:11:45] [CRITICAL] [WarframeMarket] src\wfm_client\client.rs:170:17, Could not parse response: , Error("EOF while parsing a value", line: 1, column: 0) The request failed with status code 200 to the url: https://api.warframe.market/v1/items/blood_rush/orders with the following message: EOF while parsing a value at line 1 column 0, {"ApiError":{"body":{},"error":"RequestError","messages":["EOF while parsing a value at line 1 column 0"],"method":"GET","raw_response":"","statusCode":200,"url":"https://api.warframe.market/v1/items/blood_rush/orders"}}
`

The program will cancel live trading when this error happens.

**Comment by Kenya-DK** [comment]
Dose it happens every time.
It looks like a error from wfm

**Comment by vladdavydenko** [comment]
Happens relatively often, got it a few times since the update

**Comment by pavlovdalibor** [comment]
Also happens on v1.03 - quite often
